// index.adoc
= User API
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview-http-REST]]
== HTTP Method

YOUSINSA REST API에서 사용하는 HTTP Method는 REST 방식으로 작성되었습니다.

|===
| Method | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

코드가 변경됨에 따라 추가할 예정입니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스의 제거를 성공적으로 수정함.

| `205 Reset Content`
| 기존 리소스의 제거를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `401 Unauthorized`
| 인증이 필요한 리소스

| `404 Not Found`
| 요청한 리소스가 없음.
|===

== User-API

=== SignUp

operation::user-signup[snippets='curl-request,http-request,http-response,request-body,request-fields,response-body,response-fields']

=== Withdraw

operation::user-withdraw[snippets='curl-request,http-request,http-response,path-parameters']

=== SignIn

operation::user-signin[snippets='curl-request,http-request,http-response,request-body,request-fields,response-body,response-fields']

=== SignOut

operation::user-signout[snippets='curl-request,http-request,http-response']

== Admin-API

=== Accept Store Request

operation::admin-store-accept[snippets='curl-request,http-request,http-response,request-body,request-fields,response-body,response-fields']
